name: Add Comment to Pull Request

on:
  pull_request:

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ORG_GH_APPS_ID }}
          private-key: ${{ secrets.ORG_GH_APPS_PRIVATE_TOKEN }}
          owner: Orgcongembed

      - name: Add comment to pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "GH Apps comments."
            })
