name: Add Comment to Pull Request

on:
  pull_request:

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.Demo_congneb1_app_id }}
          private-key: ${{ secrets.Demo_congneb1_private_key }}
          owner: congneb

      - name: Add comment to pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "GH Apps comments."
            })
      - name: approve
        run: |
          echo ${{ github.event.pull_request.number }}
          
          curl -X POST \
          -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/congneb/STM32-Basic//pulls/${{ github.event.pull_request.number }}/reviews \
          -d '{
            "event": "APPROVE"
          }'
        
