name: Use git App

on: 
  push:
    paths:
      - .github/workflows/build.yml

jobs:
  clone-other-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'congneb/test_build'

