name: Use git App

on: 
  push:
    paths:
      - .github/workflows/build.yml

jobs:
  clone-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.GH_APPS_ID }}
          application_private_key: ${{ secrets.GH_APPS_KEY }}
          
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          repository: 'congneb/test_build'

